safe: true
lsi: false
pygments: true

relative_source: ../book/
destination: ../openingscience.github.io/

# Settings for deploy rake task
github_user: openingscience
source_repo: book
destination_repo: openingscience.github.io

permalink: none

paginate: 50
paginate_path: "page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

title: Opening Science
name: Opening Science
url: http://book.openingscience.org
editors:
 - name:  SÃ¶nke Bartling
 - name:  Sascha Friesike

chapters:
 - name: Preface
   path: preface
 - name: Basics/Background
   path: basics_background
 - name: Tools
   path: tools
 - name: Vision
   path: vision
 - name: Cases & Recipes & How Tos
   path: cases_recipes_howtos

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.

production_url:  http://book.openingscience.org
source_url:      http://github.com/openingscience/book
archive_path:    /archive.html
categories_path: /chapters.html
tags_path:       /tags.html
rss_path:        /rss.xml
atom_path:       /atom.xml

## Markdown Parser (standard Jekyll argument, extended to special parser)
markdown: pandoc
pandoc:
  skip: true
  flags: '--smart --mathjax --filter pandoc-citeproc --bibliography=bibliography/references.bib --csl=_styles/harvard1.csl'
  outputs:
    epub:
    pdf:

comments:
  provider: disqus
  disqus:
    short_name : openingscience

# analytics :
#     provider : google
#     google :
#         tracking_id :

scholar:
  style: ./_styles/harvard1.csl
  source: ./bibliography
  bibliography: references.bib
  bibtex_filters:
    - latex
    - markdown